theme: jekyll-theme-slate
title: The Bear's Den
author: JÃ¶rg Sommrey
description: Enter at your own risk
url: https://github.sommrey.de/the-bears-den
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
